[build]
builder = "RAILPACK"
buildCommand = "bun install && bun run build"
watchPatterns = ["apps/web/**", "packages/**"]

[deploy]
startCommand = "bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.variables]
VITE_API_URL = "https://api-production-8cf1.up.railway.app"

[environments.production]
deploy.restartPolicyType = "ON_FAILURE"
deploy.restartPolicyMaxRetries = 5

[environments.pr]
deploy.restartPolicyType = "NEVER"