[build]
builder = "nixpacks"
buildCommand = "bun install && bun run build"
watchPaths = ["apps/web/**", "packages/shared/**"]

[deploy]
startCommand = "bun run start"
restartPolicyType = "never"

[deploy.variables]
NODE_ENV = "production"
VITE_API_URL = "https://ai-text-editorapi-production.up.railway.app"